-- MySQL Script generated by MySQL Workbench
-- Tue 22 Dec 2015 03:01:52 AM CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema internal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `internal` ;

-- -----------------------------------------------------
-- Schema internal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `internal` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `internal` ;

-- -----------------------------------------------------
-- Table `internal`.`groups`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`groups` ;

CREATE TABLE IF NOT EXISTS `internal`.`groups` (
  `group_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(64) NOT NULL COMMENT '',
  `description` VARCHAR(64) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`group_id`)  COMMENT '',
  UNIQUE INDEX `name` (`name` ASC)  COMMENT '');


-- -----------------------------------------------------
-- Table `internal`.`entity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`entity` ;

CREATE TABLE IF NOT EXISTS `internal`.`entity` (
  `entity_id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `type` VARCHAR(45) NULL COMMENT '',
  `created_at` DATETIME NULL COMMENT '',
  `updated_at` DATETIME NULL COMMENT '',
  `deleted_at` DATETIME NULL COMMENT '',
  `title` VARCHAR(80) NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  PRIMARY KEY (`entity_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`member` ;

CREATE TABLE IF NOT EXISTS `internal`.`member` (
  `entity_id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `member_number` INT NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `password` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `reset_token` CHAR(34) NULL DEFAULT NULL COMMENT '',
  `reset_expire` INT(11) NULL DEFAULT NULL COMMENT '',
  `firstname` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `lastname` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `civicregno` CHAR(13) NULL DEFAULT NULL COMMENT '',
  `company` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `orgno` VARCHAR(12) NULL DEFAULT NULL COMMENT '',
  `address` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `address2` VARCHAR(255) NULL DEFAULT NULL COMMENT '',
  `zipcode` INT(11) NULL DEFAULT NULL COMMENT '',
  `city` VARCHAR(64) NULL DEFAULT NULL COMMENT '',
  `country` CHAR(2) NULL DEFAULT 'SE' COMMENT '',
  `phone` VARCHAR(64) NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`entity_id`)  COMMENT '',
  UNIQUE INDEX `email` (`email` ASC)  COMMENT '',
  CONSTRAINT `fk_member_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `internal`.`entity` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `internal`.`member_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`member_group` ;

CREATE TABLE IF NOT EXISTS `internal`.`member_group` (
  `member_id` INT(11) NOT NULL COMMENT '',
  `group_id` INT(11) NOT NULL COMMENT '',
  INDEX `member_groups` (`member_id` ASC, `group_id` ASC)  COMMENT '',
  INDEX `group_id` (`group_id` ASC)  COMMENT '',
  CONSTRAINT `member_groups_ibfk_2`
    FOREIGN KEY (`member_id`)
    REFERENCES `internal`.`member` (`entity_id`)
    ON DELETE CASCADE,
  CONSTRAINT `member_groups_ibfk_1`
    FOREIGN KEY (`group_id`)
    REFERENCES `internal`.`groups` (`group_id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT);


-- -----------------------------------------------------
-- Table `internal`.`member_rfid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`member_rfid` ;

CREATE TABLE IF NOT EXISTS `internal`.`member_rfid` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `created_at` DATETIME NOT NULL COMMENT 'Timestamp',
  `updated_at` DATETIME NOT NULL COMMENT '',
  `member_id` INT(11) NOT NULL COMMENT '',
  `active` TINYINT(1) NOT NULL COMMENT '',
  `tagid` VARCHAR(255) NOT NULL COMMENT '',
  `description` TEXT NULL COMMENT '',
  PRIMARY KEY (`id`, `created_at`)  COMMENT '',
  UNIQUE INDEX `tagid` (`tagid` ASC)  COMMENT '',
  INDEX `member_id` (`member_id` ASC)  COMMENT '',
  CONSTRAINT `member_rfid_ibfk_1`
    FOREIGN KEY (`member_id`)
    REFERENCES `internal`.`member` (`entity_id`)
    ON DELETE CASCADE
    ON UPDATE RESTRICT);


-- -----------------------------------------------------
-- Table `internal`.`config`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`config` ;

CREATE TABLE IF NOT EXISTS `internal`.`config` (
  `key` VARCHAR(64) NOT NULL COMMENT 'Config key-name',
  `value` VARCHAR(2048) NULL DEFAULT NULL COMMENT '',
  `desc` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Optional description of config',
  PRIMARY KEY (`key`)  COMMENT '');


-- -----------------------------------------------------
-- Table `internal`.`logins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`logins` ;

CREATE TABLE IF NOT EXISTS `internal`.`logins` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `member_id` INT(11) NULL DEFAULT NULL COMMENT '',
  `ip_address` VARCHAR(64) NOT NULL COMMENT '',
  `timestamp` INT(11) NOT NULL COMMENT '',
  `valid` TINYINT(4) NOT NULL DEFAULT '0' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `user_id` (`member_id` ASC)  COMMENT '');


-- -----------------------------------------------------
-- Table `internal`.`accounting_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`accounting_category` ;

CREATE TABLE IF NOT EXISTS `internal`.`accounting_category` (
  `entity_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`entity_id`)  COMMENT '',
  CONSTRAINT `fk_accounting_category_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `internal`.`entity` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`accounting_verification_series`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`accounting_verification_series` ;

CREATE TABLE IF NOT EXISTS `internal`.`accounting_verification_series` (
  `entity_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`entity_id`)  COMMENT '',
  UNIQUE INDEX `entity_id_UNIQUE` (`entity_id` ASC)  COMMENT '',
  CONSTRAINT `fk_accounting_verification_series_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `internal`.`entity` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`accounting_period`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`accounting_period` ;

CREATE TABLE IF NOT EXISTS `internal`.`accounting_period` (
  `entity_id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `start` DATETIME NULL COMMENT '',
  `end` DATETIME NULL COMMENT '',
  PRIMARY KEY (`entity_id`)  COMMENT '',
  UNIQUE INDEX `entity_id_UNIQUE` (`entity_id` ASC)  COMMENT '',
  CONSTRAINT `fk_accounting_period_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `internal`.`entity` (`entity_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`accounting_instruction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`accounting_instruction` ;

CREATE TABLE IF NOT EXISTS `internal`.`accounting_instruction` (
  `entity_id` INT(11) NOT NULL COMMENT '',
  `instruction_number` VARCHAR(16) NULL COMMENT '',
  `accounting_date` DATE NULL COMMENT '',
  `accounting_category` INT(11) NULL COMMENT '',
  `importer` VARCHAR(45) NULL COMMENT '',
  `external_id` VARCHAR(255) NULL COMMENT '',
  `external_date` DATE NULL COMMENT '',
  `external_text` TEXT NULL COMMENT '',
  `external_data` TEXT NULL DEFAULT NULL COMMENT '',
  `accounting_verification_series` INT(11) NULL COMMENT '',
  `accounting_period` INT NOT NULL COMMENT '',
  PRIMARY KEY (`entity_id`)  COMMENT '',
  INDEX `accounting_category` (`accounting_category` ASC)  COMMENT '',
  INDEX `accounting_verification_series` (`accounting_verification_series` ASC)  COMMENT '',
  INDEX `instruction_number` (`instruction_number` ASC)  COMMENT '',
  INDEX `accounting_date` (`accounting_date` ASC)  COMMENT '',
  INDEX `index6` (`importer` ASC)  COMMENT '',
  INDEX `fk_accounting_instruction_4_idx` (`accounting_period` ASC)  COMMENT '',
  INDEX `index8` (`accounting_period` ASC)  COMMENT '',
  CONSTRAINT `fk_accounting_instruction_1`
    FOREIGN KEY (`accounting_category`)
    REFERENCES `internal`.`accounting_category` (`entity_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_instruction_2`
    FOREIGN KEY (`accounting_verification_series`)
    REFERENCES `internal`.`accounting_verification_series` (`entity_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_instruction_3`
    FOREIGN KEY (`entity_id`)
    REFERENCES `internal`.`entity` (`entity_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_instruction_4`
    FOREIGN KEY (`accounting_period`)
    REFERENCES `internal`.`accounting_period` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`accounting_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`accounting_account` ;

CREATE TABLE IF NOT EXISTS `internal`.`accounting_account` (
  `entity_id` INT NOT NULL COMMENT '',
  `account_number` INT NOT NULL COMMENT '',
  `accounting_period` INT NOT NULL COMMENT '',
  PRIMARY KEY (`entity_id`)  COMMENT '',
  INDEX `fk_accounting_account_1_idx` (`accounting_period` ASC)  COMMENT '',
  CONSTRAINT `fk_accounting_account_1`
    FOREIGN KEY (`accounting_period`)
    REFERENCES `internal`.`accounting_period` (`entity_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_account_2`
    FOREIGN KEY (`entity_id`)
    REFERENCES `internal`.`entity` (`entity_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`accounting_cost_center`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`accounting_cost_center` ;

CREATE TABLE IF NOT EXISTS `internal`.`accounting_cost_center` (
  `entity_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`entity_id`)  COMMENT '',
  CONSTRAINT `fk_accounting_cost_center_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `internal`.`entity` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`accounting_transaction`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`accounting_transaction` ;

CREATE TABLE IF NOT EXISTS `internal`.`accounting_transaction` (
  `entity_id` INT(11) NOT NULL COMMENT '',
  `accounting_instruction` INT(11) NOT NULL COMMENT '',
  `accounting_account` INT(11) NOT NULL COMMENT '',
  `accounting_cost_center` INT(11) NULL COMMENT '',
  `amount` INT NULL COMMENT '',
  `external_id` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`entity_id`)  COMMENT '',
  INDEX `fk_accounting_transactions_1_idx` (`accounting_instruction` ASC)  COMMENT '',
  INDEX `fk_accounting_transactions_2_idx` (`accounting_account` ASC)  COMMENT '',
  INDEX `fk_accounting_transactions_3_idx` (`accounting_cost_center` ASC)  COMMENT '',
  CONSTRAINT `fk_accounting_transactions_1`
    FOREIGN KEY (`accounting_instruction`)
    REFERENCES `internal`.`accounting_instruction` (`entity_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_transactions_2`
    FOREIGN KEY (`accounting_account`)
    REFERENCES `internal`.`accounting_account` (`entity_id`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_transactions_3`
    FOREIGN KEY (`accounting_cost_center`)
    REFERENCES `internal`.`accounting_cost_center` (`entity_id`)
    ON DELETE SET NULL
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounting_transaction_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `internal`.`entity` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`transaction_member`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`transaction_member` ;

CREATE TABLE IF NOT EXISTS `internal`.`transaction_member` (
  `member_id` INT(11) NOT NULL COMMENT '',
  `accounting_transaction_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`member_id`)  COMMENT '',
  INDEX `fk_transaction_member_2_idx` (`accounting_transaction_id` ASC)  COMMENT '',
  CONSTRAINT `fk_transaction_member_1`
    FOREIGN KEY (`member_id`)
    REFERENCES `internal`.`member` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_member_2`
    FOREIGN KEY (`accounting_transaction_id`)
    REFERENCES `internal`.`accounting_transaction` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`subscription` ;

CREATE TABLE IF NOT EXISTS `internal`.`subscription` (
  `entity_id` INT(11) NOT NULL COMMENT '',
  `member_id` INT(11) NOT NULL COMMENT '',
  `date_start` DATETIME NULL COMMENT '',
  `duration` INT(4) NULL COMMENT '',
  PRIMARY KEY (`member_id`)  COMMENT '',
  INDEX `fk_subscription_1_idx` (`entity_id` ASC)  COMMENT '',
  CONSTRAINT `fk_subscription_1`
    FOREIGN KEY (`member_id`)
    REFERENCES `internal`.`member` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_subscription_2`
    FOREIGN KEY (`entity_id`)
    REFERENCES `internal`.`entity` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`transaction_subscription`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`transaction_subscription` ;

CREATE TABLE IF NOT EXISTS `internal`.`transaction_subscription` (
  `subscription_id` INT(11) NOT NULL COMMENT '',
  `accounting_transaction_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`subscription_id`, `accounting_transaction_id`)  COMMENT '',
  INDEX `fk_labaccess_transaction_2_idx` (`accounting_transaction_id` ASC)  COMMENT '',
  CONSTRAINT `fk_labaccess_transaction_1`
    FOREIGN KEY (`subscription_id`)
    REFERENCES `internal`.`subscription` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_labaccess_transaction_2`
    FOREIGN KEY (`accounting_transaction_id`)
    REFERENCES `internal`.`accounting_transaction` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`invoice` ;

CREATE TABLE IF NOT EXISTS `internal`.`invoice` (
  `entity_id` INT NOT NULL COMMENT '',
  `invoice_number` INT NULL COMMENT '',
  `date_invoice` DATE NULL COMMENT '',
  `conditions` INT(3) NULL COMMENT '',
  `our_reference` VARCHAR(80) NULL COMMENT '',
  `your_reference` VARCHAR(80) NULL COMMENT '',
  `address` TEXT NULL COMMENT '',
  `status` VARCHAR(45) NULL COMMENT '',
  `currency` VARCHAR(3) NULL COMMENT '',
  `accounting_period` INT NOT NULL COMMENT '',
  PRIMARY KEY (`entity_id`)  COMMENT '',
  INDEX `index2` (`invoice_number` ASC)  COMMENT '',
  INDEX `index3` (`date_invoice` ASC)  COMMENT '',
  INDEX `index4` (`status` ASC)  COMMENT '',
  INDEX `index5` (`accounting_period` ASC)  COMMENT '',
  CONSTRAINT `fk_invoice_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `internal`.`entity` (`entity_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_2`
    FOREIGN KEY (`accounting_period`)
    REFERENCES `internal`.`accounting_period` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`invoice_post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`invoice_post` ;

CREATE TABLE IF NOT EXISTS `internal`.`invoice_post` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `entity_id` INT NOT NULL COMMENT '',
  `type` VARCHAR(20) NULL COMMENT '',
  `title` TEXT NULL COMMENT '',
  `price` INT NULL COMMENT '',
  `vat` INT(3) NULL COMMENT '',
  `amount` INT NULL COMMENT '',
  `unit` VARCHAR(20) NULL COMMENT '',
  `weight` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_invoice_post_1_idx` (`entity_id` ASC)  COMMENT '',
  CONSTRAINT `fk_invoice_post_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `internal`.`invoice` (`entity_id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`entity_revision`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`entity_revision` ;

CREATE TABLE IF NOT EXISTS `internal`.`entity_revision` (
  `entity_id` INT NOT NULL COMMENT '',
  `revision_date` DATETIME NULL COMMENT '',
  PRIMARY KEY (`entity_id`)  COMMENT '',
  CONSTRAINT `fk_entity_revision_1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `internal`.`entity` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `internal`.`relation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `internal`.`relation` ;

CREATE TABLE IF NOT EXISTS `internal`.`relation` (
  `entity1` INT NOT NULL COMMENT '',
  `entity2` INT NOT NULL COMMENT '',
  PRIMARY KEY (`entity2`, `entity1`)  COMMENT '',
  INDEX `fk_relation_1_idx` (`entity1` ASC)  COMMENT '',
  CONSTRAINT `fk_relation_1`
    FOREIGN KEY (`entity1`)
    REFERENCES `internal`.`entity` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_relation_2`
    FOREIGN KEY (`entity2`)
    REFERENCES `internal`.`entity` (`entity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `internal`.`entity`
-- -----------------------------------------------------
START TRANSACTION;
USE `internal`;
INSERT INTO `internal`.`entity` (`entity_id`, `type`, `created_at`, `updated_at`, `deleted_at`, `title`, `description`) VALUES (1, 'accounting_period', NULL, NULL, NULL, 'Räkneskapsår 2013', NULL);
INSERT INTO `internal`.`entity` (`entity_id`, `type`, `created_at`, `updated_at`, `deleted_at`, `title`, `description`) VALUES (2, 'accounting_period', NULL, NULL, NULL, 'Räkneskapsår 2014', NULL);
INSERT INTO `internal`.`entity` (`entity_id`, `type`, `created_at`, `updated_at`, `deleted_at`, `title`, `description`) VALUES (3, 'accounting_period', NULL, NULL, NULL, 'Räkneskapsår 2015', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `internal`.`accounting_period`
-- -----------------------------------------------------
START TRANSACTION;
USE `internal`;
INSERT INTO `internal`.`accounting_period` (`entity_id`, `name`, `start`, `end`) VALUES (1, '2013', '2013-01-01', '2013-12-31');
INSERT INTO `internal`.`accounting_period` (`entity_id`, `name`, `start`, `end`) VALUES (2, '2014', '2014-01-01', '2014-12-31');
INSERT INTO `internal`.`accounting_period` (`entity_id`, `name`, `start`, `end`) VALUES (3, '2015', '2015-01-01', '2015-12-31');

COMMIT;

